name: medicare_fwa
version: "1.0.0"
config-version: 2
profile: medicare_fwa

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  medicare_fwa:
    +materialized: table
    staging:
      +schema: stg
    marts:
      +schema: mart
