-- One-time Snowflake setup for MedicareFWA. Run in a Snowsight worksheet as ACCOUNTADMIN.
-- Replace <PUBLIC_KEY> with the key printed by `uv run fwa sf-keygen` (one line, no BEGIN/END lines).

USE ROLE ACCOUNTADMIN;

-- compute: smallest size, suspends after 60 s idle so the trial credits last
CREATE WAREHOUSE IF NOT EXISTS FWA_WH WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- storage: raw (loaded files), stg and mart (built by dbt)
CREATE DATABASE IF NOT EXISTS MEDICARE_FWA;
CREATE SCHEMA IF NOT EXISTS MEDICARE_FWA.RAW;
CREATE SCHEMA IF NOT EXISTS MEDICARE_FWA.STG;
CREATE SCHEMA IF NOT EXISTS MEDICARE_FWA.MART;

-- least-privilege role that owns the project's objects
CREATE ROLE IF NOT EXISTS FWA_ROLE;
GRANT USAGE, OPERATE ON WAREHOUSE FWA_WH TO ROLE FWA_ROLE;
GRANT USAGE ON DATABASE MEDICARE_FWA TO ROLE FWA_ROLE;
GRANT ALL ON SCHEMA MEDICARE_FWA.RAW  TO ROLE FWA_ROLE;
GRANT ALL ON SCHEMA MEDICARE_FWA.STG  TO ROLE FWA_ROLE;
GRANT ALL ON SCHEMA MEDICARE_FWA.MART TO ROLE FWA_ROLE;
GRANT ROLE FWA_ROLE TO ROLE SYSADMIN;

-- service user for scripts and dbt: key-pair only (Snowflake blocks passwords for SERVICE users)
CREATE USER IF NOT EXISTS FWA_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = FWA_ROLE
  DEFAULT_WAREHOUSE = FWA_WH
  DEFAULT_NAMESPACE = MEDICARE_FWA.STG
  RSA_PUBLIC_KEY = '<PUBLIC_KEY>';
GRANT ROLE FWA_ROLE TO USER FWA_SVC;

-- optional: cap spend on the trial
CREATE RESOURCE MONITOR IF NOT EXISTS FWA_MONITOR WITH CREDIT_QUOTA = 20
  TRIGGERS ON 90 PERCENT DO SUSPEND ON 100 PERCENT DO SUSPEND_IMMEDIATE;
ALTER WAREHOUSE FWA_WH SET RESOURCE_MONITOR = FWA_MONITOR;
